apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-service

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: v57pl22ch9omxpexyttvzrxvpj3m7/product-service
    newTag: latest
