apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: user-service
  labels:
    app: user-service
spec:
  replicas: 1 # You can adjust replicas as needed
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service-container
          image: v57pl22ch9omxpexyttvzrxvpj3m7/user-service
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
