apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: user-service

resources:
  - deployment.yaml
  - service.yaml

# This 'images' section is where Argo CD Image Updater will make its changes.
# Initial tag for user-service. Ensure this is a valid existing tag on Docker Hub.
images:
  - name: v57pl22ch9omxpexyttvzrxvpj3m7/user-service
    newTag: latest
