name: Go Microservices CI

on:
  push:
    branches:
      - main # This workflow will run on pushes to the 'main' branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Specifies the operating system for the runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Static Code Analysis using SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization="oliashish"
            -Dsonar.projectKey="oliashish_devops-ms-project"

      - name: Build User Service
        run: |
          cd user-service
          go mod tidy # Ensures go.mod and go.sum are in sync
          go build -v -o main . # Builds the executable named 'main'

      - name: Build Product Service
        run: |
          cd product-service
          go mod tidy
          go build -v -o main . # Builds the executable named 'main'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build User Service Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./user-service
          push: true
          tags: user-service:latest

      - name: Build Product Service Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./product-service # Build context is the product-service directory
          push: true
          tags: product-service:latest
